name: Python Testing Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Installing dependencies
      run: ./ci install
    - name: lint
      run: ./ci lint
    - name: unittest
      run: ./ci unittest
    - name: nose2
      run: ./ci nose2
    - name: pytest
      run: ./ci pytest
